# Permalinks
permalink:        pretty

# Setup
title:               OMDoc
tagline:             'OMDoc is an extensible standard for representing the semantics of mathematical objects.'
description:         'OMDoc is an extensible standard for representing the semantics of mathematical objects.'
url:                 http://openmath.github.io
baseurl:             ''
paginate:            5
paginate_path:       "/news/page:num/"
future:              True
gems:
  - jemoji
  - jekyll-paginate
  - jekyll-github-metadata

exclude: ['_activities/README.md', '*.synctex.gz', '*.aux', '*.nav', '*.out', '*.snm', '*.tex', '*.log', '*.toc']

# About/contact
author:
  name:              'Michael Kohlhase'
  url:                   http://omdoc.org
  email:               om-sc@openmath.org 
#  twitter:             openmath

repository:          OMDoc/OMDoc.github.io

collections:
  activities:
    output: true

# Custom vars
version:             0.2.0
