# Permalinks
permalink:        pretty

# Setup
title:               OMDoc
tagline:             OMDoc (Open Mathematical Documents) is a format for encoding STEM documents and knowledge
 '
description:         ' OMDoc (Open Mathematical Documents) is a format for encoding STEM documents and knowledge'
url:                 http://OMDoc.github.io
baseurl:             ''
paginate:            5
paginate_path:       "/news/page:num/"
future:              True
gems:
  - jemoji
  - jekyll-paginate
  - jekyll-github-metadata

exclude: ['_activities/README.md', '*.synctex.gz', '*.aux', '*.nav', '*.out', '*.snm', '*.tex', '*.log', '*.toc']

# About/contact
author:
  name:              'Michael Kohlhase'
  url:                   http://omdoc.org
  email:               kohlhase@kwarc.info
#  twitter:             OMDoc

repository:          OMDoc/OMDoc.github.io

collections:
  activities:
    output: true

# Custom vars
version:             0.2.0
